### ISSUE TITLE
Sitemap.xml Response ContentType

### ISSUE THREAD

**Issue by ddprince-yaksa** [patrickdemooij9/SeoToolkit.Umbraco#106]
Hello, 

Based on a couple of threads found online, i.e. https://stackoverflow.com/a/3272572, it seems it's recommended to put "application/xml" instead of "text/xml" for the response content type of any sitemap.xml files. This way, the encoding is automatically determined based on the XML document defined charset. 

Tools such as this one also reports similar issues: https://www.xml-sitemaps.com/validate-xml-sitemap.html. 

Would it be possible to either change the default or offer an option to change the response content type? As I've found inside the source code, under the SitemapMiddleware.cs file, it's currently hardcoded with "text/xml". 

Thanks!

**Comment by patrickdemooij9** [comment]
Hi @ddprince-yaksa 

Interesting... I had not expected such a difference between the two. I'll check on this and create a new version so that this can get fixed or at least changed with a config.

**Comment by patrickdemooij9** [comment]
Hi @ddprince-yaksa 
This issue should now be resolved in the 2.1.1 version of SeoToolkit. If you could try and verify that it also works for you, then that would be greatly appreciated 🙏

**Comment by ddprince-yaksa** [comment]
@patrickdemooij9 I just checked and it seems all good! Thanks again! :)
