### ISSUE TITLE
Allow MetaFields mapping to use RichText and Content Blocks etc.

### ISSUE THREAD

**Issue by robertjf** [patrickdemooij9/SeoToolkit.Umbraco#114]
Currently when I configure the Meta Fields for a Document Type, the only properties that are showing up for mapping are TextString and TextArea type fields.

It would be great if we could map RichText and ContentBlock properties as well - particularly for the Meta/Social Description - in this case, SeoToolkit should extract the content and strip any html etc.; looking specifically for rich text/text properties and use the first one that it finds, truncating the rest.

**Comment by patrickdemooij9** [comment]
Hi @robertjf 
Adding the RichText sounds like a logical inclusion. I'll make sure that one is added. 
As for the ContentBlock properties, how would you see that working? As SeoToolkit doesn't know how you will render your ContentBlocks so it can't really predict how the HTML of that will look like. 

It is possible to do this in code through one of the notifications: https://seotoolkit.gitbook.io/useotoolkit/extensions/notifications#beforemetatagsnotification. But if you have a suggestion for how it would work, then that would be great!

**Comment by robertjf** [comment]
Hey @patrickdemooij9,

As a ContentBlock model is a structured json object, we can iteratively walk through the blocks looking for certain property types (after all, they are just IPublishedElements) and aggregate the first text strings that we find (including Rich text) until we have enough to satisfy the length of the meta field (title or description), truncating the rest.

This way, it wouldn't matter what the structure or layout of the blocks is at all - we can only take a best-guess as to what the editor is trying to convey in the page anyway :)

**Comment by patrickdemooij9** [comment]
Just so to double-check that we are thinking about the same thing.

If we have a page with a property (ContentBlock) called 'content' and the content of 'content' looks like this:

- Hero
  - Title
  - Text
  - CallToAction
- TextBlock
  - Title
  - Text
- Form
  - Title
  - Form
- TextBlock
  - Title
  - Text

We could have a way to select the first hero block with a special syntax (dunno if this is the best way to do it, but it'll work for this example). Something like content.Hero[0].Title, which will get the first Hero block in the `content` property and then the 'Title' property of that block.
And something like content.TextBlock.Text that will iterate all TextBlocks under 'content' and append the 'Text' property until the length is reached.

Is this what you were thinking about?

I think this would be quite cool, although making an interface for this might be a bit troubling but I am sure that can be done.

**Comment by patrickdemooij9** [comment]
Yeah, that would probably be best for a first version, but it is good to hear that we are thinking about the same thing here 😊

I am sure I'll pick it up the future as well, but pull requests are always appreciated too!

**Comment by robertjf** [comment]
yep, will see what I can do 👍🏻

**Comment by robertjf** [comment]
At the moment, the pull request only looks at top-level block list/grid items and extracts any text / text area / tinymce content it finds.  It should probably also truncate the result based on a configurable value, but doesn't yet.

**Comment by robertjf** [comment]
@patrickdemooij9 any idea on when you're likely to schedule a release?  Itching to get these changes into production...

**Comment by patrickdemooij9** [comment]
> @patrickdemooij9 any idea on when you're likely to schedule a release? Itching to get these changes into production...

Took a bit longer than expected, but it is out now: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.4.0. Thanks again for your help on this!
