### ISSUE TITLE
Meta Fields property editors 404 when viewing SEO App

### ISSUE THREAD

**Issue by robertjf** [patrickdemooij9/SeoToolkit.Umbraco#115]
On Umbraco 10.2.0-rc with SeoToolkit.Umbraco 2.1.2, attempting to view the SEO properties for a content node comes up with a lot of 404 errors (see below image).
I've attempted to uninstall and reinstall the nuget package but still get the same result:

![image](https://user-images.githubusercontent.com/818101/188916062-c79f6584-8b50-422c-a2d0-c0fd8536b86e.png)

**Comment by patrickdemooij9** [comment]
That is interesting. I'll see if I can find the reason for this. Thank you for the report!

**Comment by patrickdemooij9** [comment]
Hi @robertjf
I had some time to check this out, but I can't reproduce it. I have a clean umbraco installation (10.2.0-rc) and then the latest version of SeoToolkit, but the views are all present for me.

Do you have any special configuration that could cause it? And what is the full URL that is shown in the network tab? Maybe that could shed some more light on this error.

**Comment by robertjf** [comment]
hm.  Well, I've just updated the project to Umbraco 10.2.0 and the problem persists - aha! it's a case sensitivity issue:
I'm running this on MacOS, so of course the filesystem is case-sensitive.

Umbraco users all lowercase - `textbox.html` etc. while SeoToolkit is calling for `TextBox.html` and friends:

![image](https://user-images.githubusercontent.com/818101/189081520-bff54528-3163-4812-9aef-0185a6af1d62.png)

**Comment by patrickdemooij9** [comment]
Ah, then it makes sense why it cannot find it. I also don't have a Mac to test it on so this never occurred to me. I'll make sure to get this fixed!

**Comment by patrickdemooij9** [comment]
Hi @robertjf 

Sorry that it took so long to fix, but this has now been fixed in the lastest release!

**Comment by robertjf** [comment]
Thanks @patrickdemooij9 - will check it out today...

**Comment by robertjf** [comment]
Thanks @patrickdemooij9 - tested and working well :)

**Comment by patrickdemooij9** [comment]
Woohoo! Thank you for testing and reporting the issue
