### ISSUE TITLE
Custom Domain redirects

### ISSUE THREAD

**Issue by TimBoonstra** [patrickdemooij9/SeoToolkit.Umbraco#118]
It looks as if custom domain redirects arent working.

My site is setup with 2 domains, 1 is configured as hostname in umbraco, the other one is not.
When i create a redirect rule, with custom domain, relative from url /
and then try to redirect to the home content, or explicitly configured url it gets stuck in a "too many redirects".

I have to link both both host names in umbraco, so that i can create a direct from the 2nd hostname to the first.

Also when you setup a relative from url as / it is not shown in the list interface, which means you are unable to "edit" the link later on unless you change the html manually

**Comment by patrickdemooij9** [comment]
Hi @TimBoonstra 

Thanks for the report!
I'll see if I can reproduce it and then roll out a fix for it

**Comment by patrickdemooij9** [comment]
I can reproduce it with these settings:
![image](https://user-images.githubusercontent.com/11466511/192606242-09bc4652-101c-4c43-a852-61974043526a.png)

Fix coming up!

**Comment by patrickdemooij9** [comment]
@TimBoonstra 
This should now be fixed in the latest release (2.1.4)
