### ISSUE TITLE
Getting 500 error after enabling SEO App for doctype (Sitemap properties) in Umbraco 10

### ISSUE THREAD

**Issue by martinjgriffiths** [patrickdemooij9/SeoToolkit.Umbraco#121]
I'm experiencing the following error in my local build (Umbraco 10, SQL Express)

![image](https://user-images.githubusercontent.com/883638/193788175-31be2279-0956-481e-a2ee-aa8fbec1c227.png)

**Comment by patrickdemooij9** [comment]
@martinjgriffiths 
I can't quite reproduce this. It does show an empty content app for me, so I'll have a look at that, but I will need some more information to figure this one out.

**Comment by patrickdemooij9** [comment]
This should now also be fixed with this PR: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/127
Newest version is currently planned for next week
