### ISSUE TITLE
mydomain.ch/robot.txt 404 Error

### ISSUE THREAD

**Issue by apload-gmbh** [patrickdemooij9/SeoToolkit.Umbraco#134]
Hi

We use Umbraco 9.5.0 and like to start with SeoToolkits robot.txt feature. Umbraco 9 uses .Net 5 and therefore we use SeoToolkit v.1.1.0.

According to your docs, we installed it via (VS2022) NuGet package manager, added the taghelfpers in _ViewImports.cshtml and rebuilded our project. Finally, we were able to enter some basic "code" in the robot.txt entry field in the package of Umbracos backend, but if we try to browse mydomain.ch/robot.txt we get a 404 error.

Is there anything we are missing? Something in the appsettings.json?

Thanks for your help.

Kind regards

Jan

**Comment by patrickdemooij9** [comment]
Hi @apload-gmbh 

Thank you for the report. I am not quite sure what is going wrong here as there shouldn't be any additional configuration needed. I do see that you are refering to /robot.txt, but that should be robots.txt. Could that perhaps be the reason for it?

If that isn't it, I'll have to see if I can reproduce this issue.

Kind regards,
Patirck

**Comment by apload-gmbh** [comment]
OMG! Shame on me. Robots.txt it should be.
Please do accept my apologizes and delete this conversation.

**Comment by patrickdemooij9** [comment]
No problem. Happy to hear that it is working as expected instead of there being an issue!
