### ISSUE TITLE
Section not available for Robots txt

### ISSUE THREAD

**Issue by lumimario** [patrickdemooij9/SeoToolkit.Umbraco#138]
I have installed SeoToolkit.Umbraco.RobotsTxt version 3.0.0 on an Umbraco version 10.3.1 and I can't see the section to manage it. I have check if I had to give the Administrators group permissions, but the section doesn't event appear on the available list.

**Comment by patrickdemooij9** [comment]
Hi @lumimario 
The 3.0.0 version is for Umbraco 11. If you want to try the Robots.txt package, I suggest you to download the 2.2.0 version. That one should work with your Umbraco version.
Kinda strange that Nuget allows you to pick the 3.0.0 version, will have to take a look at that.

**Comment by lumimario** [comment]
ah cool, thanks for that.
