### ISSUE TITLE
Possible to set meta keywords?

### ISSUE THREAD

**Issue by ianleeder** [patrickdemooij9/SeoToolkit.Umbraco#139]
Similar to #123, I'm kind of surprised to find that I can't set Keywords.

Any progress on updating the [wiki](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/wiki/Meta-Fields)?
![image](https://user-images.githubusercontent.com/8241300/194298332-fb93ca9d-105a-4e14-9625-c1d70fe05b07.png)

**Comment by colinfyfe** [comment]
Hi @ianleeder, I've just discovered this package today and hats off to @patrickdemooij9 as it covers 99% of my use cases too with meta tags, sitemap.xml, GTM and Hubspot integration being the immediate boxes ticked. I'm new to both .NET and Umbraco but Patrick's TODO encouraged me to dive into the source to see if I could figure this one out. I'm not saying this is correct - Patrick might recoil in horror when he sees this implementation - but I've added a custom keywords field between the description and canonical URL.

![seotoolkit-keywords-field](https://user-images.githubusercontent.com/6955259/210184613-d5b6e39b-69da-4dcf-9910-bd8d76ad0448.png)

I created an SeoKeywordsField class based on a modified [SeoDescriptionField](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/blob/d0408a97411574b95c73c7b709897fd5c9d0de2c/src/SeoToolkit.Umbraco.MetaFields.Core/Models/SeoField/SeoDescriptionField.cs):

```csharp
using Microsoft.AspNetCore.Html;
using SeoToolkit.Umbraco.MetaFields.Core.Common.SeoFieldEditEditors;
using SeoToolkit.Umbraco.MetaFields.Core.Constants;
using SeoToolkit.Umbraco.MetaFields.Core.Interfaces.SeoField;
using SeoToolkit.Umbraco.MetaFields.Core.Models.SeoFieldEditors;
using Umbraco.Cms.Core.Composing;

namespace Cf.Umbraco.Extensions
{
    [Weight(210)]
    public class SeoKeywordsField : ISeoField
    {
        public string Title => "Meta Keywords";
        public string Alias => "metaKeywords";
        public string Description => "Meta keywords for the page";
        public string GroupAlias => SeoFieldGroupConstants.MetaFieldsGroup;
        public Type FieldType => typeof(string);

        public ISeoFieldEditor Editor => new SeoFieldFieldsEditor(new[] { "Umbraco.TextBox", "Umbraco.TextArea", "Umbraco.TinyMCE" });

        public ISeoFieldEditEditor EditEditor => new SeoTextAreaEditEditor();

        public HtmlString Render(object value)
        {
            return new HtmlString($"<meta name='keywords' content='{value}'/>");
        }
    }
}
```

... then created an Umbraco IComposer to register the new type:

```csharp
using SeoToolkit.Umbraco.MetaFields.Core.Collections;
using SeoToolkit.Umbraco.MetaFields.Core.Composers;
using Umbraco.Cms.Core.Composing;

namespace Cf.Umbraco.Extensions
{
    [ComposeBefore(typeof(MetaFieldsComposer))]
    public class SeoKeywordComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.WithCollectionBuilder<SeoFieldCollectionBuilder>().Add<SeoKeywordsField>();
        }
    }
}
```

This hasn't been extensively tested and I'll let Patrick advise on whether it's the right approach or not but it certainly seems to be working for me in my local dev environment.

**Comment by patrickdemooij9** [comment]
Totally missed this issue, so sorry for the late reply.

What @colinfyfe has posted is indeed the correct way of doing this. It is exactly the way that I would have done it. And I should indeed update the documentation with these examples. 

As for why the package doesn't have meta keywords is because they aren't used by Google anymore (and many other search providers). Is there a reason on why you would need them @ianleeder? Would love to hear the use case for them if they aren't used that much anymore.

**Comment by ianleeder** [comment]
Wow.  Thanks for this example @colinfyfe.  Even if I don't use it for Keywords, it still may come in very handy.

@patrickdemooij9 I obviously haven't kept up to date on SEO techniques!  The client included keywords on their wishlist somewhere, but if it's no longer used for SEO I'll simply pass that on to them.  Thanks.
