### ISSUE TITLE
SEO (meta) settings lost during uSync

### ISSUE THREAD

**Issue by ianleeder** [patrickdemooij9/SeoToolkit.Umbraco#149]
I was planning to spend a little more time investigating and replicating this issue, but I'm fairly confident there is a problem, so I'm rush-reporting just in case it's an easy fix for you to slot into the next release.  I've seen your name attached to some uSync tickets/forums, so I'm assuming it should be supported.  Feel free to close if not.

It seems that SEO settings are not synchronised with uSync (I'm using Complete Publisher).

**Settings are not carried from my source to my target.**  
~Settings that were previously set on the target are lost after a sync.~

**Comment by patrickdemooij9** [comment]
We currently don't have any connections with uSync yet. There is a PR in the work (https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/105) that I have to work on a bit more, but I don't think it'll be an easy thing to get implemented.

**Comment by ianleeder** [comment]
Ok no problems.  I was mainly worried that sync was overwriting/nuking existing settings, but I think it was probably document type changes being synced that may have done that.  That won't be a problem once development is finished.  I'm happy to set up SEO settings on each server.
