### ISSUE TITLE
Add the sitemap: xxx automatically to the robots.txt

### ISSUE THREAD

**Issue by dampee** [patrickdemooij9/SeoToolkit.Umbraco#157]
It seems that the sitemap is not added to the robots.txt automatically while the two modules are installed.  Is this normal behavior?

**Comment by patrickdemooij9** [comment]
Yeah, it isn't smart enough to combine them yet. I've an issue for it here: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/7. I might be able to get this working for the next release this weekend, but can't promise anything

**Comment by patrickdemooij9** [comment]
This should now automatically work with the latest releases (Fixed in 2.3.0 & 3.1.0 (https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.1.0)). Let me know if you find any issues with it.
