### ISSUE TITLE
How can you add the sitename of the website to the title tag for every page?

### ISSUE THREAD

**Issue by dampee** [patrickdemooij9/SeoToolkit.Umbraco#158]
I am searching for a way to add the sitename at the end of the page title for every page. I cannot find an easy way to do this. 

Eg.

Current situation:

    <title>My pagename</title>

wanted situation

    <title>My pagename - The Best Builders</title>

**Comment by patrickdemooij9** [comment]
There is a way to do this through code by using the AfterMetaTagsNotification (https://seotoolkit.gitbook.io/useotoolkit/extensions/notifications#aftermetatagsnotification). I'll see if I can create an example for you after my work today

**Comment by patrickdemooij9** [comment]
Hi @dampee,
Sorry about the example being a bit later than expected. Using something like this in your code should give you the ability to add the sitename at the end of the title:
```
public class ExampleAfterMetaTagsNotification : INotificationHandler<AfterMetaTagsNotification>
    {
        public void Handle(AfterMetaTagsNotification notification)
        {
            notification.MetaTags.Title += "- The Best Builders";
        }
    }
```

Let me know if you have any more questions about this
