### ISSUE TITLE
robots.txt sitemap values are incorrect

### ISSUE THREAD

**Issue by kmai-universe** [patrickdemooij9/SeoToolkit.Umbraco#164]
SeoToolkit produces the following output in the robots.txt file:

Sitemap: /sitemap.xml
Sitemap: /en/sitemap.xml
etc.

It is not allowed to use relative paths in the robots.txt file. See here:
https://developer.chrome.com/docs/lighthouse/seo/invalid-robots-txt/?utm_source=lighthouse&utm_medium=lr

This makes pagespeed.web.dev produce an error.

Correct format should be:

sitemap: https://<absolute url>/sitemap.xml
sitemap: https://<sbsolute url>/en/sitemap.xml

**Comment by patrickdemooij9** [comment]
Hi @kmai-universe 
That is indeed not the correct value. I'll make sure that it gets fixed in the next couple days!

**Comment by patrickdemooij9** [comment]
Fixed by https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/164. Will be released soon
