### ISSUE TITLE
Sitemap.xml is not generate anything

### ISSUE THREAD

**Issue by aphwong** [patrickdemooij9/SeoToolkit.Umbraco#165]
My site have this three main document type
![image](https://user-images.githubusercontent.com/43560054/222392736-8217d0d9-b38f-44a1-ad58-ff5290ef1673.png)
and this is the sitemap structure
![image](https://user-images.githubusercontent.com/43560054/222394629-7c8ef879-0df1-440e-be47-72db9f840017.png)

I've enabled the SEO on the these document types and content.
![image](https://user-images.githubusercontent.com/43560054/222392842-d7bf8d65-28d4-4afd-be26-377116bab70d.png)

![image](https://user-images.githubusercontent.com/43560054/222395931-a4918a95-41cc-4567-a65b-0eada45d480d.png)

But there are only two domain information are shown up,
in the path "https://localhost:44304/sitemap.xml"
![image](https://user-images.githubusercontent.com/43560054/222394992-38dff619-5b56-4c03-aeb9-4004a67f2255.png)

**Comment by patrickdemooij9** [comment]
Hi @aphwong 
Do all those 3 root items have a domain configured to them?
Also, did you do something with the sitemap.xml to have those <link> and <style> elements show up? I don't think that they should be in the sitemap generated by the package

**Comment by aphwong** [comment]
Hi @patrickdemooij9 , thanks for replying me.
domain configure <-- you mean here?
<img width="601" alt="image" src="https://user-images.githubusercontent.com/43560054/222527426-ee5ae196-de04-4898-8ddd-363e711ec10d.png">

![image](https://user-images.githubusercontent.com/43560054/222528270-6f92cc6c-8cb0-4b2b-9edf-2ef0b5da7000.png)


Give you more information. I am using Umbraco CMS as headless CMS, therefore the front-end domain is different from back-end(CMS domain).

**Comment by patrickdemooij9** [comment]
Yeah, those domains are coming back into the sitemap.xml so that is good. So what exactly is going wrong? Or what would you want to see differently?

**Comment by aphwong** [comment]
Because only "Home" document type loc is shown now.
I expect other children node will also shown in the sitemap

**Comment by patrickdemooij9** [comment]
That is because it generates a sitemapindex here. The sitemapindex shows references to the actual sitemaps. If you go to one of your domains/sitemap.xml, you should see the pages of your website.

**Comment by patrickdemooij9** [comment]
Hi @aphwong 
As I haven't heard back from you in recent times, I'll assume that this issue is now fixed and therefore close the issue. If this still occurs, please reopen the issue.
