### ISSUE TITLE
Metafields property labels

### ISSUE THREAD

**Issue by kows** [patrickdemooij9/SeoToolkit.Umbraco#168]
When defining the fallbacks for metadata on your doc types you only see the property labels.
Since this isn't forced to be unique you are uncertain which property you are applying.

Possible info which can help out:
- Alias
- Group
- Tab
- ... ?

Would need changes in:
- ItemGroupPicker
- SeoFieldEditors

Would like your thoughts on how you'd like to see this being applied.

**Comment by patrickdemooij9** [comment]
Good point. I think it would be good to group them and maybe also show the alias somewhere. That should go a long way to being able to distinguish them between other properties

**Comment by patrickdemooij9** [comment]
This has now been released as part of the latest release: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.2.0
