### ISSUE TITLE
Using a single quote in meta fields leads to invalid HTML

### ISSUE THREAD

**Issue by philipdanielhayton** [patrickdemooij9/SeoToolkit.Umbraco#176]
Hi Patrick,

I've just noticed that the meta tag attributes use single quotes, which leads to invalid markup when the value itself contains a single quote.

For example if the og:title is set to "What's on" then the markup looks like this

    <meta property='og:title' content='What's on in' />

I don't think it's a massive issue but it's flagging as an error in https://validator.w3.org.

**Comment by patrickdemooij9** [comment]
That will indeed cause some issues. I'll get on it right away!

**Comment by patrickdemooij9** [comment]
Fixed by commit https://github.com/patrickdemooij9/SeoToolkit.Umbraco/commit/2e41c7dd83d3f06be8fef4021992c2cd8282f812. Will try to get a new version out tomorrow

**Comment by philipdanielhayton** [comment]
Legend, thanks for fixing so quickly!

**Comment by patrickdemooij9** [comment]
This has been fixed in the latest versions! Thanks again for the report
