### ISSUE TITLE
Truncate error saving Meta description

### ISSUE THREAD

**Issue by wvduffelen** [patrickdemooij9/SeoToolkit.Umbraco#179]
While saving a long Meta description (more than 255 characters) you get an error. The frontend mention the SEO description is saved but when you go back to the SEO-tab the content isn't there. 

The error in the log Viewer is:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table '{dbName}.dbo.SeoToolkitMetaFieldsValue', column 'UserValue'. Truncated value: '"{textValue} '.

The statement has been terminated.
```

When I add a shorter piece of text all goes well.  I've checked this in Version `2.2.0` and `2.3.2`

### To replicate this error:

1. Add long content to the meta description or open graph description
2. Save the content (It will give feedback that the content is saved)
3. Move away from the content (Discard changes when you go to another page)
4. Open the page with the meta description you've just changed and see that is missing
5. Check your Umbraco Log Viewer and you'll see the error I mentioned earlier

**Comment by patrickdemooij9** [comment]
Hi @wvduffelen,
Thank you for the report. That is indeed an annoying error :/ I'll give it a look and make sure it is fixed

**Comment by patrickdemooij9** [comment]
Fixed by https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/181. Will deploy a new version within the coming days. Thanks again for reporting!

**Comment by wvduffelen** [comment]
Thanks @patrickdemooij9! We'll just wait for the new version then!

**Comment by patrickdemooij9** [comment]
I actually managed to push the update yesterday. So you should be able to update to the latest version now!
