### ISSUE TITLE
No URLs are coming in Sitemap XML

### ISSUE THREAD

**Issue by nilaydigiwhiz** [patrickdemooij9/SeoToolkit.Umbraco#186]
I am using SEOTool kit for One of my Umbraco 9 projects and when i open /sitemap.xml, only sitemap.xml url is listed over there nothing else

**Comment by nilaydigiwhiz** [comment]
Resolved. It was issue with culture and hostname

**Comment by PezCo** [comment]
How did you resolve it exactly? i'm having a similar issue.
I have a Hostname site at root node and exploring the site using that hostname works as expected but i only get /sitemap.xml it the list of urls on sitemap page

**Comment by nilaydigiwhiz** [comment]
Is hostname matching your domain / website address? e.g. if the domain is with www then need to add with www in hostname / cluture

**Comment by patrickdemooij9** [comment]
I'll be closing the issue as it doesn't seem like an issue anymore. If you still have issues with it, then please reopen or create a new issue
