### ISSUE TITLE
Missing twitter meta tags

### ISSUE THREAD

**Issue by danilovulovic** [patrickdemooij9/SeoToolkit.Umbraco#191]
I installed the latest version of SeoTookit on Umbraco 11, everything works great except it misses twitter meta tags, as well as og:url meta tag.

How I can fix it?

**Comment by patrickdemooij9** [comment]
Hi @danilovulovic 
Those tags are indeed not supported at the moment. They do serve a purpose, so I'll check about adding them to the package. In the meantime, there is a way to create your own meta tags. This PR: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/198 also adds some, so perhaps you can see how that works (I haven't had time to write the documentation for them yet)

**Comment by patrickdemooij9** [comment]
This has now been added in the latest release: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.4.0
