### ISSUE TITLE
Provide reference to original content node when generating metadata

### ISSUE THREAD

**Issue by ianleeder** [patrickdemooij9/SeoToolkit.Umbraco#193]
Same as issue #144, I would like to have access to the content node in the metadata notification events.

My use-case looks like something like this (our region handling is a hack, not the official way):
```cs
public void Handle(AfterMetaTagsNotification notification)
{
    // Handle region-specific metadata
    if(region is "NZ" &&
        !string.IsNullOrWhiteSpace(notification.Content.Value<string>("metaDataTitleNZ")))
    {
        notification.MetaTags.Title = notification.Content.Value<string>("metaDataTitleNZ");
    }
}
```

I have less concerns about performance on this than the sitemap: this is only storing the content object once, the sitemap notification event was potentially tracking hundreds of content objects.

**Comment by ianleeder** [comment]
I'm migrating a legacy site that already has a lot of checkboxes for things like "Hide from sitemap", "MetaDataTitle", "ExcludeRobotsCrawl" etc.  Although the correct way would be to use the native SeoToolkit settings for these, there are hundreds of pages.  It's easier to hook into the metadata event and set the values based upon the content node, than it is to republish or migrate the content.

**Comment by patrickdemooij9** [comment]
And this one has also been released with the latest version! https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.2.0
