### ISSUE TITLE
Add RobotsField to the MetaTagsModel for access during notifications

### ISSUE THREAD

**Issue by ianleeder** [patrickdemooij9/SeoToolkit.Umbraco#195]
Would it be possible to add [`RobotsField`](src/SeoToolkit.Umbraco.MetaFields.Core/Models/SeoField/RobotsField.cs) to the [`MetaTagsModel`](src/SeoToolkit.Umbraco.MetaFields.Core/Models/SeoService/MetaTagsModel.cs) so that it can be used in the notifications handler?

**Comment by patrickdemooij9** [comment]
This has now been released with the latest version! https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.2.0
