### ISSUE TITLE
Multilingual is not updating

### ISSUE THREAD

**Issue by Navorski** [patrickdemooij9/SeoToolkit.Umbraco#202]
If the website is configured with multiple languages, changing the language is not updating the SEO Content App for that language automatically.
![changelanguage](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/7352877/41857399-06b3-4de1-b2b4-e66d14926b62)

Umbraco Version: v10.5.1
SeoToolkit Version: v2.4.0

**Comment by patrickdemooij9** [comment]
Hi @Navorski 
That indeed doesn't look correct. Great catch! Will check it out and get a fix out there

**Comment by patrickdemooij9** [comment]
Fixed by https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/208. Will be in the next deployment
