### ISSUE TITLE
My sitemap.xml is in plain text.

### ISSUE THREAD

**Issue by WebWolves-be** [patrickdemooij9/SeoToolkit.Umbraco#205]
Hi

For some reason my sitemap.xml is showing in plain text :

![afbeelding](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/75836706/56b6a86d-16f0-4e5a-afe8-78b7d017ed58)

This is the url : https://www.chiropracticbelgium.be/sitemap.xml

I am also working with a hostname per language:

![afbeelding](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/75836706/1ddb55ac-1b8f-472a-ae12-eea45314b587)

What could be the problem? Is the first time I am using this package and I am fairly new to Umbraco as well. Any help is much appreciated!

**Comment by patrickdemooij9** [comment]
Hi @WebWolves-be 
This should be correct. If you look at the network tab of the sitemap request, you'll see that it returns the correct content type: 
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/11466511/afb09602-3fa8-45a6-90a8-d11c87681d37)

But for whatever reason, browsers always show it like this. application/xml is the preferred content-type to be returned here though.

**Comment by Ambertvu** [comment]
Hmm, this isn't entirely consistent though.

I have a root node without any languages using the root domain, this shows actual XML output:

```
<urlset xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://localhost:44383/</loc>
<lastmod>2023-08-08</lastmod>
</url>
</urlset>
```

I also have a second root node, but with domains assigned to it, this shows the 'plain text but content type is application/xml' variant:

https://localhost:44383/nl/ 2023-08-08 https://localhost:44383/nl/testpage-1/ 2023-07-31 https://localhost:44383/nl/testpage-2/ 2023-07-31 https://localhost:44383/nl/testpage-3/ 2023-07-31 https://localhost:44383/nl/testpage-4/ 2023-07-31 https://localhost:44383/nl/test-page-5/ 2023-07-25 https://localhost:44383/nl/contact/ 2023-07-25 https://localhost:44383/nl/testpagina-7/ 2023-07-25 https://localhost:44383/nl/nieuwsoverzicht/ 2023-07-31
