### ISSUE TITLE
SEO Content App is installed without functioning (2.4.0)

### ISSUE THREAD

**Issue by Ambertvu** [patrickdemooij9/SeoToolkit.Umbraco#217]
When installing the below packages you only have access to the robots.txt section and a sitemap is generated.

SeoToolkit.Umbraco 2.4.0:
.Common
.RobotsTxt
.RobotsTxt.Core
.Sitemap.Core

However in the Document Types screen a new SEO content app also appears:
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/13347420/2f368875-60e6-4fd1-ad40-ee180fc1273f)
This however, is unfunctional, as there are no views installed. It would be best if the app would not appear at all when there are no settings.

**Comment by patrickdemooij9** [comment]
Good point! We now add UI-related components in the core projects which shouldn't know anything about the UI. I've now split them in https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/224 so that this issue doesn't happen anymore

**Comment by patrickdemooij9** [comment]
Has been released with this release: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.3.0
