### ISSUE TITLE
[BUG] SeoToolkit.Redirects Unable to select a page that resides under Collection View

### ISSUE THREAD

**Issue by grafsnikers** [patrickdemooij9/SeoToolkit.Umbraco#220]
I can't select a page that resides under page with enabled collection view, because the Green Button "Submit" isn't showing and I get an error message in the console, see screenshot below:
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/47172346/4766bafd-c141-4ae0-871f-153cc39f5884)
The Error message: 
`$apply @ angular.js:19622
(anonymous) @ angular.js:29127
dispatch @ jquery.min.js?d=638276793750000000:2
v.handle @ jquery.min.js?d=638276793750000000:2
umbraco#/SeoToolkit/Redirects/list?mculture=en-US:1 An invalid form control with name='textbox' is not focusable. <input type=​"text" id=​"url" name=​"textbox" ng-model=​"model.value" class=​"umb-property-editor umb-textstring textstring ng-pristine ng-untouched ng-isolate-scope ng-valid-val-server ng-empty ng-invalid ng-invalid-required" val-server=​"value" ng-required=​"model.validation.mandatory" aria-required=​"true" aria-invalid=​"false" ng-trim=​"false" ng-change=​"change()​" ng-readonly=​"readonly" required=​"required">​
`

Installed packages:
`<TargetFramework>net7.0</TargetFramework>`
`<PackageReference Include="Our.Umbraco.MultilanguageTextbox" Version="12.0.0" />`
`<PackageReference Include="SeoToolkit.Umbraco.MetaFields" Version="3.2.0" />`
`<PackageReference Include="SeoToolkit.Umbraco.Redirects" Version="3.2.0" />`
`<PackageReference Include="Umbraco.Cms" Version="12.0.1" />`
`<PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />`
`<PackageReference Include="Umbraco.TheStarterKit" Version="11.0.0" />`

Steps to reproduce:
1) Install Umbraco.TheStarterKit
2) Install SeoToolkit.Umbraco.Redirects
3) Try to create a redirect to a blog page

**Comment by patrickdemooij9** [comment]
Hi @grafsnikers,

Thanks for the report! I've taken a look and the error doesn't seem related to it (also not quite sure why the error is there), so I have created a different issue for that: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/221. 
As for your issue, it has been fixed with this commit: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/commit/4213d2ca58c7cd6283ab54b3c248612a1da55da4

**Comment by grafsnikers** [comment]
Great, thanks a lot!

**Comment by patrickdemooij9** [comment]
Fix is now available in the latest release: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.3.0
