### ISSUE TITLE
Redirect doesn't work if select 'Regex' and 'All Sites'

### ISSUE THREAD

**Issue by irinamakovetskaya** [patrickdemooij9/SeoToolkit.Umbraco#227]
https://github.com/patrickdemooij9/SeoToolkit.Umbraco/blob/414e6c9d94f81cfca9123882d152b13910f84cc3/src/SeoToolkit.Umbraco.Redirects.Core/Services/RedirectsService.cs#L154
                    if (it.Domain?.Id == 0) return true; 
// it.Domain is null if you select 'All Sites' and redirect don't used, you need to add check for null too

**Comment by patrickdemooij9** [comment]
Fixed by https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/242. Thanks for the detailed report! I hope you'll give it a try when the new version comes live
