### ISSUE TITLE
Scheduled Content

### ISSUE THREAD

**Issue by ThomasGrant08** [patrickdemooij9/SeoToolkit.Umbraco#229]
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/110394805/8060ac1f-fe4a-4d38-89f1-b8efec6dac8c)

Unpublished Content does not have meta fields available to edit in anticipation of a scheduled publish.

Umbraco Version: 11.4.2

SeoToolkit Version: 3.1.1

**Comment by patrickdemooij9** [comment]
Hmm, interesting that it doesn't show any meta fields at all.

I'll take a look at what is happening here.

**Comment by ThomasGrant08** [comment]
Thanks, if you need any further information, let me know.

Once it publishes, the fields do show up.

**Comment by patrickdemooij9** [comment]
This should be fixed with https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/244 and will be included in the next version
