### ISSUE TITLE
Missing info about regex in docs

### ISSUE THREAD

**Issue by henryson** [patrickdemooij9/SeoToolkit.Umbraco#230]
I am trying to add a redirect in SEO Toolkit and I want to use the regex function. There is one example in the docs and I tried to use that example but I don't get it to work. 

I want an URL with language 'sv' to remove that URL segment like this: 

www.domain.com/sv/mypage => www.domain.com/mypage

This is my attempt in SEO Toolkit: 

^/sv/?(.*) = /$1

It does not work. I am a bit familiar with regex but not how it is expected to be used in this context. 

So this issue is about extending the docs, but I would also appreciate help with my specific problem :-)

Cheers and thanks for a great package!

Josef/

**Comment by grafsnikers** [comment]
This might be related to https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/227

**Comment by patrickdemooij9** [comment]
Hi @henryson 
Sorry for the late reply. This was indeed causing by a bug in the code if your redirect was set to All Sites
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/11466511/01098ce1-4aff-4b98-891c-9fc91fafe118)

This will be fixed in the latest version of SeoToolkit
