### ISSUE TITLE
Meta tags are not generating, what I'm missing?

### ISSUE THREAD

**Issue by renaldas** [patrickdemooij9/SeoToolkit.Umbraco#239]
Umbraco version 12.2.0

Installed packages, added 

@addTagHelper *, uSeoToolkit.Umbraco.ScriptManager.Core
@addTagHelper *, uSeoToolkit.Umbraco.MetaFields.Core

into _ViewImports.cshtml, but tags are not rendering, just stays: <meta-fields></meta-fields>

SEO enabled and fields filled.

What I'm missing here, stuck...

**Comment by renaldas** [comment]
uSeoToolkit should be without SeoToolkit

**Comment by patrickdemooij9** [comment]
Hi @renaldas 
Happy to hear that you figured it out! Was the uSeoToolkit should somewhere in the documentation? If so, then I'll change it so other people don't run into this issue
