### ISSUE TITLE
support dotnet 8.0 - umbraco < 12.999

### ISSUE THREAD

**Issue by DanielOberlechner** [patrickdemooij9/SeoToolkit.Umbraco#253]
Hi I wanted to update my website to umbraco 13.0.0-rc2 but this package is only with umbraco < 12.999 compatible.
Have you in mind updating the package to newer umbraco next time soon, or do we have to wait for a longer time?

Kind regards,
Daniel

**Comment by patrickdemooij9** [comment]
Hi @DanielOberlechner 
Support for Umbraco 13 has now been added: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.5.0
