### ISSUE TITLE
Umbraco 13 support

### ISSUE THREAD

**Issue by robertjf** [patrickdemooij9/SeoToolkit.Umbraco#258]
Add support for Umbraco 13

See Pull Request #257  👍🏻

**Comment by robertjf** [comment]
@patrickdemooij9 Happy Holidays :) Let me know if you need any assistance with this - really keen to start building Umbraco 13 sites with this package.

**Comment by aguyfromdenmark** [comment]
@patrickdemooij9, What is the outlook for Umbraco 13 support. I would love to test SeoToolkit out to see if it can replace out current setup, but it has to work on Umbraco 13.

**Comment by patrickdemooij9** [comment]
Umbraco 13 support has now been released: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.5.0
