### ISSUE TITLE
Update to dot net core 8 SeoToolkitRedirects | SqliteException: SQLite Error 1: 'no such column: SeoToolkitRedirects.IsEnabled'.

### ISSUE THREAD

**Issue by DanielOberlechner** [patrickdemooij9/SeoToolkit.Umbraco#262]
Hi i get the dollowing update error message after updateing to the new version dot net core 8.0

Is there any special step to do. I don;t have it overall enabled only for a few templates ....

Kind regards,
Daaniel

**Comment by DanielOberlechner** [comment]
Solved issue by manually adding this field and make it integer with value 1 ... Probably got forgotten to mention in programming .... now it looks at the first moment as it works

@patrickdemooij9 
FYI

**Comment by DanielOberlechner** [comment]
Issue happened somehow again and now again needs fix.
What possible solutions do we have here?

Error happens even if redirect plugin is not installed .... 

Kind rergards,
Daniel

**Comment by DanielOberlechner** [comment]
*push
this error still exists and bugs me to hell ... can't run softeware anymore to a stable point ....

**Comment by patrickdemooij9** [comment]
Hi @DanielOberlechner 
Do you perhaps have the full stacktrace available for me? It sounds like a migration didn't run correctly for you.

**Comment by DanielOberlechner** [comment]
`An unhandled exception occurred while processing the request.
SqliteException: SQLite Error 1: 'no such table: SeoToolkitRedirects'.
Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db)

Stack Query Cookies Headers Routing
SqliteException: SQLite Error 1: 'no such table: SeoToolkitRedirects'.
Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db)
Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection+CommandWrapper.ExecuteDbDataReader(CommandBehavior behavior)
StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs
Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand+<>c__DisplayClass35_0.<ExecuteDbDataReader>b__0()
Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand+<>c__DisplayClass38_0<T>.<Execute>b__0()
Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction<TResult>(Func<TResult> func)
Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute<T>(Func<T> f)
Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
NPoco.Database+<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()
NPoco.Database.ExecutionHook<T>(Func<T> action)
NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
NPoco.Database.ExecuteDataReader(DbCommand cmd, bool sync)
NPoco.AsyncHelper.RunSync<T>(Task<T> task)
NPoco.Database.QueryImp<T>(T instance, Expression<Func<T, IList>> listExpression, Func<T, object[]> idFunc, Sql Sql, PocoData pocoData)+MoveNext()
System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
NPoco.Database.Fetch<T>(Sql sql)
SeoToolkit.Umbraco.Redirects.Core.Repositories.RedirectsRepository.GetByUrls(string[] paths)
SeoToolkit.Umbraco.Redirects.Core.Services.RedirectsService.GetByUrl(Uri uri)
SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.HandleRedirect(HttpContext context)
SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.Invoke(HttpContext context)
SeoToolkit.Umbraco.Sitemap.Core.Middleware.SitemapMiddleware.Invoke(HttpContext context, ISitemapGenerator sitemapGenerator, ISitemapIndexGenerator sitemapIndexGenerator)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
`

**Comment by DanielOberlechner** [comment]
> `
An unhandled exception occurred while processing the request. SqliteException: SQLite Error 1: 'no such table: SeoToolkitRedirects'. Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db)
> 
> Stack Query Cookies Headers Routing SqliteException: SQLite Error 1: 'no such table: SeoToolkitRedirects'. Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db) Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext() Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext() Microsoft.Data.Sqlite.SqliteDataReader.NextResult() Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior) Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection+CommandWrapper.ExecuteDbDataReader(CommandBehavior behavior) StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand+<>c__DisplayClass35_0.b__0() Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand+<>c__DisplayClass38_0.b__0() Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Func func) Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute(Func f) Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) NPoco.Database+<>c__DisplayClass298_0.b__0() NPoco.Database.ExecutionHook(Func action) NPoco.Database.ExecuteReaderHelper(DbCommand cmd) NPoco.Database.ExecuteDataReader(DbCommand cmd, bool sync) NPoco.AsyncHelper.RunSync(Task task) NPoco.Database.QueryImp(T instance, Expression<Func<T, IList>> listExpression, Func<T, object[]> idFunc, Sql Sql, PocoData pocoData)+MoveNext() System.Collections.Generic.List..ctor(IEnumerable collection) System.Linq.Enumerable.ToList(IEnumerable source) NPoco.Database.Fetch(Sql sql) SeoToolkit.Umbraco.Redirects.Core.Repositories.RedirectsRepository.GetByUrls(string[] paths) SeoToolkit.Umbraco.Redirects.Core.Services.RedirectsService.GetByUrl(Uri uri) SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.HandleRedirect(HttpContext context) SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.Invoke(HttpContext context) SeoToolkit.Umbraco.Sitemap.Core.Middleware.SitemapMiddleware.Invoke(HttpContext context, ISitemapGenerator sitemapGenerator, ISitemapIndexGenerator sitemapIndexGenerator) Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) `

**Comment by DanielOberlechner** [comment]
`
SqliteException: SQLite Error 1: 'no such table: SeoToolkitRedirects'.
Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db)

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: SeoToolkitRedirects'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Umbraco.Cms.Persistence.Sqlite.Services.SqlitePreferDeferredTransactionsConnection.CommandWrapper.ExecuteDbDataReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 204
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass35_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)
   at NPoco.AsyncHelper.RunSync[T](Task`1 task)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at SeoToolkit.Umbraco.Redirects.Core.Repositories.RedirectsRepository.GetByUrls(String[] paths)
   at SeoToolkit.Umbraco.Redirects.Core.Services.RedirectsService.GetByUrl(Uri uri)
   at SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.HandleRedirect(HttpContext context)
   at SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.Invoke(HttpContext context)
   at SeoToolkit.Umbraco.Sitemap.Core.Middleware.SitemapMiddleware.Invoke(HttpContext context, ISitemapGenerator sitemapGenerator, ISitemapIndexGenerator sitemapIndexGenerator)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
`

**Comment by patrickdemooij9** [comment]
I have tried to reproduce this, but I just can't get it to throw an error. Are you perhaps able to check the database table `umbracoKeyValue` and then what the value is next to `Umbraco.Core.Upgrader.State+SeoToolkit_Redirects_Migration`?

**Comment by DanielOberlechner** [comment]
![Screenshot 2024-01-23 at 21 43 12](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/10922763/16f41070-9913-4a61-babd-a3979f3922eb)

**Comment by DanielOberlechner** [comment]
Keep in mind I tinkered around myself quite abit and now I don't know which is the first unttouched database without any of my doings. I created once the table myself, a other time i restored the database (bad idea) ... just letting you know

Evene uninstalling the redirect plugin didn't solve the problem for me just gotta say ....

**Comment by patrickdemooij9** [comment]
Hmm, it does say that all migrations are run as expected. What you could try is this:
- Remove the `Umbraco.Core.Upgrader.State+SeoToolkit_Redirects_Migration` record. This won't cause any issues and should automatically regenerate the missing table.

Though I am suprised to hear that you still have this issue after uninstalling the redirects package. You might want to check your bin folder to see that the DLL has actually been deleted. It might still be there and therefore being loaded into your application.

**Comment by DanielOberlechner** [comment]
Now it works again. I had no dll installed and simply removed the table you advised me! Thank you so much now I can progress with my website development! Now I simply installed whole paclage with redirect and everything.

Kind regards,
Daniel

**Comment by patrickdemooij9** [comment]
Great to hear that that worked! Let me know if you run into any other issues!
