### ISSUE TITLE
Manually adding content redirect's search throws error

### ISSUE THREAD

**Issue by Ambertvu** [patrickdemooij9/SeoToolkit.Umbraco#270]
When creating a redirect and setting the target of the redirect, using the Content option, you can select a page succesfully:
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/13347420/86c48307-4708-4a9b-b1bb-3aa0fd7a20ab)

However, when using the search function and then selecting a page, the submit button is removed
![image](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/13347420/97576dd3-62f4-4d09-9cc5-2a72f31b654f)

And it throws an error in console:
```
TypeError: vm.newUrlData is null
    submit https://www.xxxxxx.nl/App_Plugins/SeoToolkit/Redirects/Dialogs/createRedirect.controller.js?v=e1c6d0a4cc2199c35a64932f390a69759fb6612a:147
```

**Comment by patrickdemooij9** [comment]
Should be fixed in https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.5.1
