### ISSUE TITLE
Metafields saved multiple times on page with list view enabled

### ISSUE THREAD

**Issue by josephheqj** [patrickdemooij9/SeoToolkit.Umbraco#273]
Hi there, we are using SEO Toolkit 3.5.0 along with Umbraco 12.1.2. In list view, there is a problem with saving the Meta Fields settings. The child page’s values are overridden by the parent page. And when we published the changes, the JS save() function was called multiple times. This issue only occurred in the list view when the "Edit in Infinite Editor" option was selected.
![2024-04-24 17 45 42](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/assets/49510685/a0e7a4d2-d4de-40c8-94b7-429251521844)

**Comment by josephheqj** [comment]
#274 
One possible solution we came up with is to add a check to ensure that only the current editor's update is being saved.

**Comment by josephheqj** [comment]
One possible solution we came up with is to add a check to ensure that only the current editor's update is being saved.

See pull request #274

**Comment by patrickdemooij9** [comment]
Fixed by https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/274
