### ISSUE TITLE
Redirect with special chat not working

### ISSUE THREAD

**Issue by kmai-universe** [patrickdemooij9/SeoToolkit.Umbraco#279]
Hi,

If we make a redirect with the Danish language characters æøå then the redirect doesn't work. Is there anything special we can do to make this work or is this a bug?

We would like to redirect 
/storskærm 

I know we can do /storskaerm but in out case we already did the physical marketing material.

**Comment by patrickdemooij9** [comment]
Hi @kmai-universe 
I was able to reproduce your issue and wrote a fix for it in https://github.com/patrickdemooij9/SeoToolkit.Umbraco/commit/c46fb42e23eeffe630542ac5deb8749c3fb2e67e.
I'll see if I can push a new version this weekend or early next week so that you are able to use it straight away.

**Comment by patrickdemooij9** [comment]
Fixed in 3.5.1 (https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.5.1)
