### ISSUE TITLE
Sitemap nuget package is missing dashboard files

### ISSUE THREAD

**Issue by rosrosros** [patrickdemooij9/SeoToolkit.Umbraco#74]
Umbraco version: 9.4.1
Nuget packages installed: SeoToolkit.Umbraco.Sitemap 1.0.1

It seems some files are missing when installing just the Sitemap nuget package.

App_Plugsins folder contains only 2 files:

- App_Plugins\SeoToolkit\Sitemap\Displays\DocumentType\sitemapSettings.controller.js
- App_Plugins\SeoToolkit\Sitemap\Displays\DocumentType\sitemapSettings.html

![image](https://user-images.githubusercontent.com/1798386/166253415-d32fa6e8-7935-4c84-aa84-16a4cbd01024.png)

**Comment by patrickdemooij9** [comment]
Hmmm interesting.
I'll take a look at it tonight and let you know when I have more information! Thanks for the report!

**Comment by patrickdemooij9** [comment]
Hi @rosrosros,
The issue should now be fixed in the latest 1.0.2 version. Thanks again for the issue!

**Comment by rosrosros** [comment]
Hi @patrickdemooij9 

Works perfektly!

Fastest response ever 💪💪💪

**Comment by henryson** [comment]
I have the exact same issue, but only after publishing to live environment. Locally it is fine, but note in production. I have version 10.1.0 och Umbraco and 2.1.1 of the SIteMap package. The weird thing is that I can't find the SEOToolkit folder in my local App_Plugins folder either, but it works anyway. Is it in the DLL?

**Comment by patrickdemooij9** [comment]
> I have the exact same issue, but only after publishing to live environment. Locally it is fine, but note in production. I have version 10.1.0 of Umbraco and 2.1.1 of the SiteMap package. The weird thing is that I can't find the SEOToolkit folder in my local App_Plugins folder either, but it works anyway. Is it in the DLL?

Hi @henryson 
Since 2.1.0 all static assets have been moved to a razor package library. You won't see the files in your solution as they are used from the nuget cache.

Although, they should be copied over correctly when publishing your site so something must be going wrong there. I'll check it out this evening if I can find something. I might need some more information if I can't reproduce it

**Comment by henryson** [comment]
Thanks for your quick response!

Let me know what you need, I am glad to help. Perhaps it is just my publish routine that is failing.

Cheers, Josef

________________________________

**Comment by patrickdemooij9** [comment]
@henryson 
I just tried publishing myself and that doesn't seem to cause any issues. The SeoToolkit files should be on the published server under /wwwroot/App_Plugins/SeoToolkit. Can you check if you have them there?
I also tried 10.1.0, but that also didn't give an issue.

Also what sort of publish action are you doing? Publishing to IIS or just folder? To a windows machine or linux?

**Comment by patrickdemooij9** [comment]
Very strange... Could you describe how you are doing the publish? Are you just running the `dotnet publish`? Any parameters that you are then passing? 
It should work within VS and also with just `dotnet publish`. I've tested both and both copy the files over.

**Comment by henryson** [comment]
I will make a new attempt to publish tomorrow at work.

Regards, Josef
________________________________

**Comment by henryson** [comment]
I also tried this from terminal: dotnet publish -c Release without success. It shows me this however:

Copying pagenotfoundmanager files: C:\Users\josef.henryson\.nuget\packages\hotchilli.umbraco.pagenotfound\2.0.0\buildTransitive\..\App_Plugins\HC.PageNotFound\**\*.* - #3 files

Copying UrlTracker files: C:\Users\josef.henryson\.nuget\packages\urltracker\10.1.0\buildTransitive\..\content\App_Plugins\UrlTracker\**\*.* - #9 files

So the other packages are copied but not SEO Toolkit :-(

**Comment by patrickdemooij9** [comment]
Yeah, that is caused due to them now being included as Razor Package library. Before, SeoToolkit also had a target file, but that shouldn't be needed anymore.

And I've been able to kinda replicate it 😅 I created a new project with Umbraco (10.1.0), added SeoToolkit.Umbraco.Sitemap. Builded the solution and then tried to publish it. While successful, it didn't copy over an App_Plugins folder.
But then I ran the solution once and checked that it was running correctly locally and tried the publish again. This time it actually did copy over the App_Plugins.

Very confused, but I should be able to test a bit more with a new project.

There is something that you might be able to check. If you go to C:\Users\[Your user]\.nuget\packages\seotoolkit.umbraco.sitemap\2.1.1, then you should see two folders called staticwebassets and wwwroot. Can you check if they both have assets in them?

**Comment by henryson** [comment]
First I installed sitemap only, but then I installed all of them to see if that made a difference. 

![image](https://user-images.githubusercontent.com/8781095/187871786-31ef8795-1093-4942-9933-c688f51d2fd6.png)

![image](https://user-images.githubusercontent.com/8781095/187871887-b7037d05-d710-46ca-85ba-bf41eee701fc.png)

**Comment by patrickdemooij9** [comment]
That all looks fine too. Those are the only files needed for the sitemap. Still not sure why it doesn't publish them though..

Would you be able to reproduce this with a new Umbraco project? So the following steps:

- Install Umbraco template website (10.1.0)
- Install SeoToolkit.Umbraco.Sitemap (latest version)
- Build & run the project.
- Run `dotnet publish -c Release` and check the location that is mentioned in the command prompt.

**Comment by henryson** [comment]
I followed each step above for a new project and first I did not find an App_Plugins folder in the output.
But then I looked in the wwwroot folder and there was the App_Plugins folder containing SeoToolkit with asssets. 
But in my project the App_Plugins is not located in wwwroot.

**Comment by patrickdemooij9** [comment]
Then it sounds like it might be something related to your project here. I also downloaded the HotChilli and UrlTracker packages to see if they were the issue, but it still correctly places the files with a publish.

Is there anything in your .csproj file that could be influencing your publish? That is the only thing I can still think of. Without the rest of your project or any way to reproduce it, I am getting stuck on what it could be.

**Comment by henryson** [comment]
It seems I have managed to resolve it now! In my Mac setting I removed all SeoToolkit NuGet packages and then installed the Sitemap package only and published with dotnet publish -c Release and the the files were there in wwwroot/App_Plugins!!
I repeated the same procedure in my Windows setting and voila! the files were there as well!
So it seems like removing and adding the package was the solution (in combination with looking in the correct App_Plugins folder). Big thanks for your effort to help me out, much appreciated!!

**Comment by patrickdemooij9** [comment]
Happy to hear that you got it resolved! I would have never thought that something like that would fix it, but I am happy that it did 👍

**Comment by henryson** [comment]
Good morning!

I made a publish to folder in Visual Studio 2022 and looked at the results. Still no files in App_Plugins:

***@***.***

***@***.***

I also tried self-contained mode. Made no difference.

The DLL files are there, the package shows up in backoffice but with with tab text: [SeoToolkit] and clicking it gives red alert.

Cheers, Josef

Från: patrickdemooij9 ***@***.***>
Datum: onsdag, 31 augusti 2022 21:23
Till: patrickdemooij9/SeoToolkit.Umbraco ***@***.***>
Kopia: Josef Henryson ***@***.***>, Mention ***@***.***>
Ämne: Re: [patrickdemooij9/SeoToolkit.Umbraco] Sitemap nuget package is missing dashboard files (Issue #74)

Very strange... Could you describe how you are doing the publish? Are you just running the dotnet publish? Any parameters that you are then passing?
It should work within VS and also with just dotnet publish. I've tested both and both copy the files over.

**Comment by patrickdemooij9** [comment]
Hi @henryson 

I thought you got this working last time? Did someting change?

**Comment by henryson** [comment]
> Hi @henryson
> 
> I thought you got this working last time? Did someting change?

Hi Patrick! This is very strange, it says I wrote this comment 23 min ago. I didn't. I suspect I started to write it earlier and that it was still in an open tab or something and then got posted for some reason. Or perhaps an email reply in my drafts that got sent. I think I didn't send/post it since it was resolved but I forgot to remove the draft. Sorry about that. Do you want me to delete the comment?

And thanks for your great work and your quick response to my problem!

**Comment by patrickdemooij9** [comment]
> > Hi @henryson
> > I thought you got this working last time? Did someting change?
> 
> Hi Patrick! This is very strange, it says I wrote this comment 23 min ago. I didn't. I suspect I started to write it earlier and that it was still in an open tab or something and then got posted for some reason. Or perhaps an email reply in my drafts that got sent. I think I didn't send/post it since it was resolved but I forgot to remove the draft. Sorry about that. Do you want me to delete the comment?
> 
> And thanks for your great work and your quick response to my problem!

No it's fine, you can keep the comment there. I figured something like that would have happend. Just happy that the issue didn't come back
