### ISSUE TITLE
Sitemap package causes boot to fail

### ISSUE THREAD

**Issue by krebil** [patrickdemooij9/SeoToolkit.Umbraco#93]
When installing the sitemap package my Umbraco 10 (on umbraco cloud) installation fails to boot giving this error:

` Umbraco.Cms.Core.Exceptions.BootFailedException: SQLite Error 1: 'near "ALTER": syntax error'.`

The other packages work as expected, if I install the general package(SeoToolkit.Umbraco) I get the same error.

A little more of my stack trace:
`Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)
Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
SeoToolkit.Umbraco.Redirects.Core.Middleware.RedirectMiddleware.Invoke(HttpContext context)
SeoToolkit.Umbraco.RobotsTxt.Core.Middleware.RobotsTxtMiddleware.Invoke(HttpContext context)
SeoToolkit.Umbraco.Sitemap.Core.Middleware.SitemapMiddleware.Invoke(HttpContext context, ISitemapGenerator sitemapGenerator, ISitemapIndexGenerator sitemapIndexGenerator)
Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by krebil** [comment]
@patrickdemooij9 
Thanks for looking into it, let me know if you need anything else

**Comment by patrickdemooij9** [comment]
Will be fixed in the next release, which I will probably release somewhere over the weekend.

**Comment by patrickdemooij9** [comment]
Fixed in 2.0.1
