### ISSUE TITLE
Consider using StaticWebAsset for serving app_plugin files in dev environment

### ISSUE THREAD

**Issue by Nikkelmann** [patrickdemooij9/SeoToolkit.Umbraco#96]
Other packages ([uSync](https://github.com/KevinJump/uSync/commit/a8782b693ce69df26a2528728f973dd80611b940) / [FullTextSearch](https://github.com/skttl/umbraco-fulltextsearch8/commit/b193ffe75c107da2181a91b179061708378339af)) seem to have shifted to this approch, which avoids having the files copied over during installation of the package.

I don't know if changing the sdk to `Microsoft.NET.Sdk.Razor` and adding `<StaticWebAssetBasePath>` is the only change needed.

**Comment by patrickdemooij9** [comment]
Great suggestion! Will have to deep a bit deeper into it, but seems like the way to go in the future
